Add Hogun's house
joshua-wanjae-choi/Simcity pull request #2
Opened 2019-02-07 05:22 UTC by hogun97

2019-02-07 05:30 UTC, joshua-wanjae-choi approved these changes

2019-02-07 05:30 UTC, joshua-wanjae-choi commented on mycity
> +            $$$ 이호건 집 $$$
인덴트를 수정해주세요. 하지만 좋은 집입니다.

2019-02-07 05:30 UTC, joshua-wanjae-choi requested changes

2019-02-07 05:30 UTC, joshua-wanjae-choi commented on mycity
> +            $$$ 이호건 집 $$$
인덴트를 수정해주세요.

2019-02-09 14:36 UTC, johngrib requested changes
conflict 를 해결해 주세요.

2019-02-10 06:11 UTC, joshua-wanjae-choi commented
conflict를 해결하였습니다!

2019-02-10 06:11 UTC, merged